### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by ZHANGGUANGLONG327** [janstenum/GaitAnalysis-PoseEstimation#1]
hello!
When I run this program, step 2.3 always compresses the video to less than 1MB, resulting in only one frame of video output and many duplicate json files.
What should I do?
As I am not good at code, I would be grateful if you could give me detailed answers!
![1](https://user-images.githubusercontent.com/72990075/105049840-0f24af00-5aa8-11eb-80e8-820088aeb6b9.png)
![2](https://user-images.githubusercontent.com/72990075/105049849-121f9f80-5aa8-11eb-99a5-2dddec85103d.png)

**Comment by janstenum** [comment]
Hi, I'm not sure which step 2.3 you refer to - can you clarify? Thanks

**Comment by ZHANGGUANGLONG327** [comment]
When I use Google Colab to analyze the video, in step 2.3, the video in my Google drive i select  will be compressed to 1Mb.
Could it be a network problem？

**Comment by ZHANGGUANGLONG327** [comment]
When I upload the video from local to Google cloud disk, the video is 5MB and can be played normally. However, after step 2.3, the video will become 1MB and only the first frame will be played

**Comment by janstenum** [comment]
Hi, sorry this dropped off my radar - did you manage to solve this issue?

**Comment by ZHANGGUANGLONG327** [comment]
Not yet, but I have successfully run the code using Local Vision.
Your code has helped me a lot. How can I cite your code?

**Comment by janstenum** [comment]
OK, I'm glad to hear that you have it working. The article describing the workflow has been accepted and will be published soon - I can send the link when it's published. If you need a citation now you can use the preprint: https://www.biorxiv.org/content/10.1101/2020.07.24.218776v1.

**Comment by janstenum** [comment]
The article is available at: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008935.
