### ISSUE TITLE
Why isnt this MATLAB command working with this project?

### ISSUE THREAD

**Issue by ShadowCoder67** [janstenum/GaitAnalysis-PoseEstimation#2]
`Unrecognized function or variable 'nanmean'.

Error in calculate_gaitParameters_jointAngles (line 68)
gaitParameters.gaitSpeed = nanmean([gaitParameters.stepLength.left gaitParameters.stepLength.right])/mean([gaitParameters.stepTime.left gaitParameters.stepTime.right]);

Error in OpenPoseGaitAnalysis_JS (line 13)
calculate_gaitParameters_jointAngles(output_name);
 
`
Ive been working with this project and after running the initial command `OpenPoseGaitAnalysis_JS` I go through the other functions and once I finish the one where you enter your meters and pick 2 points, and I tape save, it provides this error.

**Comment by janstenum** [comment]
It sounds like the 'nanmean' function is not included in your MATLAB version. You can access the 'nanmean' function by downloading the Statistics Toolbox.

**Comment by ShadowCoder67** [comment]
I just did that and re-ran it yet I still run into an error. 

This is the error:
Warning: The initial magnification of the image is set to 'fit' in a docked figure. 
> In imshow (line 322)
In extractScaling_openpose (line 21)
In OpenPoseGaitAnalysis_JS (line 11) 

I am not sure whats going wrong and am just running the OpenPoseGaitAnalysis_JS and following the documentation. When I get to the part where I have to select 2 points I tap calclate scaling and then save and that error appears.

**Comment by ShadowCoder67** [comment]
Also. When I try the function calculate_gaitParameters_jointAngles(''sink') I get this error.

Warning: Variable 'events_openpose' not found. 
> In calculate_gaitParameters_jointAngles (line 7) 
Unrecognized function or variable 'events_openpose'.

Error in calculate_gaitParameters_jointAngles (line 9)
for j = 1:length(events_openpose.lhs_frames)

Please help!

**Comment by janstenum** [comment]
1. You can disregard the warning "Warning: The initial magnification of the image is set to 'fit' in a docked figure." The code is running regardless of this warning. 
2. It sounds like the gait events are not saved before the code reaches the stage at which it calculates gait parameters. In the window to inspect gait events, remember to click 1) the 'Save' button and then 2) the 'Close' button. (If you only click 'Close' the gait events are not saved.)
